spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: test  #测试环境 
  application:
    name: microservice-config-test

---
spring:
  profiles: test  #测试环境 
  application:
    name: microservice-config-test
# 保存方式 必须 utf-8 不然提交会出错            
